### ISSUE TITLE
Include network explorer links for tx details

### ISSUE THREAD

**Issue by Cooper-Kunz** [the-creators-galaxy/hts-distribution-tool#10]
## Issue
Currently it's difficult to confirm via 3rd parties the status of a distribution. 

## Potential solutions
Link all transactions, accounts, etc. to a 3rd party network explorer like [DragonGlass](https://testnet.dragonglass.me) or [Kabuto](https://explorer.kabuto.sh/testnet) (or both). 

## Questions
Is there a way a network explorer could aggregate distribution details?

**Comment by bugbytesinc** [comment]
I'm assuming this is a UI thing right now, not info we'd embed in the output CSV file.

**Comment by Cooper-Kunz** [comment]
Sorry to miss/not respond to 

> I'm assuming this is a UI thing right now, not info we'd embed in the output CSV file.

but yes, that's correct. we don't need to embed this into the .csv output
