### ISSUE TITLE
Show a Confirmation Dialog while attempting to close the application when processing.

### ISSUE THREAD

**Issue by bugbytesinc** [the-creators-galaxy/hts-distribution-tool#20]
## Issue
Currently, the the user can accidentally close the app while it is in the middle of processing a distribution plan.

## Potential solution
Add a confirmation dialog box double-checking that the user intended to close the app while in the middle of processing.

## Questions
Should that be a native confirmation dialog or something with UI branding?

**Comment by Cooper-Kunz** [comment]
I think that we could start by utilizing a native dialogue, and if needed, go through a design cycle in a later improvement.
