### ISSUE TITLE
Update distribution status message 

### ISSUE THREAD

**Issue by Cooper-Kunz** [the-creators-galaxy/hts-distribution-tool#30]
Currently the distribution status column contents include "Status: " which is implicit due to its column/categorization. 

![Screen Shot 2021-12-20 at 12 49 18 PM](https://user-images.githubusercontent.com/11776938/146817785-78bde202-2a57-4038-bb05-dec125e8ff6d.png)

Can we remove "Status: " from the contents within that column? 

e.g. "Status: Distribution Completed" -> "Distribution Completed"

**Comment by lucalves** [comment]
Hello! I believe that #32 will solve this.
