### ISSUE TITLE
Switch default network explorer to DragonGlass

### ISSUE THREAD

**Issue by Cooper-Kunz** [the-creators-galaxy/hts-distribution-tool#39]
## Issue

Currently (by default) we link to Kabuto which has been ... inconsistent on testnet (at best). 

![Screen Shot 2022-04-07 at 2 05 24 PM](https://user-images.githubusercontent.com/11776938/162277994-2eb0a06b-f75c-40df-a98b-a85c04ed691d.png)

## Solution

Let's switch to DragonGlass for the time being.

**Comment by victorholo** [comment]
You might also want to consider [https://hashscan.io](https://hashscan.io). Seems to have better HTS support compared to DragonGlass and the interface is cleaner.
