### ISSUE TITLE
Remove requirement for empty new-line on key inputs

### ISSUE THREAD

**Issue by Cooper-Kunz** [the-creators-galaxy/hts-distribution-tool#5]
## Issue
Currently when inputting private keys to the app, it requires there to be a new (empty line) prior to progressing in the user journey.

## Potential solution
Remove the requirement for a new (empty) line and process each input on text-changes. Additionally, we should consider accepting alternative key types (seed phrase, wallet connect like APIs, etc.) but that is beyond the scope of this issue & will be raised/addressed separately. 

## Questions
n/a

**Comment by bugbytesinc** [comment]
Adding some screen shots illustrating proposed UI changes

**Comment by bugbytesinc** [comment]
![image](https://user-images.githubusercontent.com/4412843/169292870-682574d7-b0e2-4557-bb36-5efa134fafa6.png)

**Comment by bugbytesinc** [comment]
Pasting into the input box or the paste button (on the right) provides feedback on the type of key (and if successful)
![image](https://user-images.githubusercontent.com/4412843/169293131-5b5daecc-e26e-4a2e-829c-d4f9db6440de.png)

**Comment by bugbytesinc** [comment]
Recognizes ecdsasecp and ed25519
![image](https://user-images.githubusercontent.com/4412843/169293272-c94c0517-1b30-42b7-8bce-1d1b0a2ced6a.png)

**Comment by bugbytesinc** [comment]
And provides reasons why it didn't recognize the key:
![image](https://user-images.githubusercontent.com/4412843/169293380-c31c2002-4308-47ec-9dbf-615fa91b39d3.png)

**Comment by bugbytesinc** [comment]
the list looks similar to before, but is explicit about key types:
![image](https://user-images.githubusercontent.com/4412843/169293642-a1d6ac34-7fdd-451f-86ab-cd9071811326.png)
