### ISSUE TITLE
Include dedicated app icon

### ISSUE THREAD

**Issue by Cooper-Kunz** [the-creators-galaxy/hts-distribution-tool#8]
## Issue
Currently the app icon that displays in a toolbar is the default Electron icon.

## Potential solution
Ask design (cough cough [Chadd Weston](https://twitter.com/ChaddWeston)) to provide a graphic they'd like to use.

## Questions
n/a

**Comment by bugbytesinc** [comment]
The icon is there for the Mac, but it is necessary to actually create a package before the Mac will display it, it appears this is not possible for "development" versions of the app on MacOS.

bookmark for later:

https://www.christianengvall.se/electron-packager-tutorial/
