### ISSUE TITLE
Update "completed" messaging in real-time details

### ISSUE THREAD

**Issue by Cooper-Kunz** [the-creators-galaxy/hts-distribution-tool#9]
## Issue 
Distributions should not be considered "complete" until they've been fully counter signed, executed, and confirmed successful. Running the instance locally results in a scenario where 25k txs could be "completed" in the sense that the operator has finished running their portion of the distribution, but the distribution itself is not yet completed. 

## Potential solution
We should differentiate when an operator has finished {submitting, signing, etc.} versus when the whole process is complete, e.g. all balances have updated, or transactions have been completed.

## Questions
What should the specific status/states be messaged as to provide as much clarity as possible?

**Comment by bugbytesinc** [comment]
Thinking of the following macro statuses:

- Not Started
- Processing
- Scheduled
- Completed
- Failed
